### ISSUE TITLE
可以添加一个在线上传的功能么

### ISSUE THREAD

**Issue by DarknessChaser** [itorr/one-last-image#1]
这样子就能在线直接生成后保存了

看了下代码可以直接拖拽进去，建议稍微完善一下说明文字

**Comment by itorr** [comment]
还在跑原型(ಥ_ಥ) 具体什么形态还没有想好

**Comment by yzhe819** [comment]
@DarknessChaser  现在代码是有的，在代码里面加个`div`连一下点击事件

```html
<div @click="chooseFile">添加本地文件</div>
```

**Comment by itorr** [comment]
> @DarknessChaser 现在代码是有的，在代码里面加个`div`连一下点击事件
> 
> ```
> <div @click="chooseFile">添加本地文件</div>
> ```

确实，现在小改了下界面🥲 纹理问题有点多，先把选图按钮加上了
