### ISSUE TITLE
透明背景的显示问题

### ISSUE THREAD

**Issue by yzhe819** [itorr/one-last-image#2]
在[测试链接](https://im.front.dog/one-last-image/html/)将生成图片另存为后本地打开会发现显示不一致，调子好像被去掉了

初步怀疑是透明背景导致了window照片的显示错误

应有的样子：
![canvas](https://user-images.githubusercontent.com/68207314/184266014-277c565f-b04b-4667-aa09-4a73e7929dca.png)

真实的显示（没截全，但大小是没问题的）：
![图片](https://user-images.githubusercontent.com/68207314/184266071-ad601147-12d5-475d-8a40-7e6763114a07.png)

BTW，或许可以加上一个是否选择纯白背景的选项

**Comment by itorr** [comment]
感谢反馈，现在起型期间仅用 alpha 通道简化了输出流程，在 canvas 下设置白色背景简单实现了预览。
可能是windows 的照片查看器对于 alpha 透明图片显示支持比较特别，看这个 真实的输出 好像半透明部分全都消失了，确实很离谱🤦🏼‍♀️。

调子这里有个铅笔痕迹的纹理还没有搞定，预计把调子的铅笔纹理搞定就把输出图像这部分确定一下方案。看来是不能直接输出带 alpha 透明的图片了🫠

**Comment by yzhe819** [comment]
感谢开发者及时的回复！！
通过更新 windows 的照片查看器，现在可以看到显示正确。
从`202.19111.24110.0`更新到`2022.30070.26007.0`可以解决预览的显示问题。
 (平时完全没有注意到它需要更新，一个版本用到微软倒闭hhh

<details>
<summary>screenshot</summary>

![图片](https://user-images.githubusercontent.com/68207314/184272707-ae5f9935-af38-4f24-85d8-82b602e060f8.png)
</details>

不过这个 issue 依然可以开着，因为将 alpha 透明的图片设置为桌面背景的时候会变得非常抽象。
在老的照片预览中将带 alpha 的像素是不显示，而在桌面背景中是带 alpha 的像素都显示为不透明的像素👇

<details>
<summary>screenshot</summary>

![图片](https://user-images.githubusercontent.com/68207314/184273633-7db7cb9b-a78b-4e2e-bb1b-2437cff3fd13.png)
</details>

**Comment by yzhe819** [comment]
好耶！现在已经被修复了，感谢💖

**Comment by itorr** [comment]
> 好耶！现在已经被修复了，感谢💖

先直接画白底输出了👻 现在演示版本 大概就是最终形态，只是可能会在调子纹理上再做些调整
