### ISSUE TITLE
寻找 One Last Kiss 标题字体

### ISSUE THREAD

**Issue by itorr** [itorr/one-last-image#3]
![image](https://user-images.githubusercontent.com/1933673/184288950-5e7d6718-d2c3-43c2-a687-e4f0a187ca62.png)
One Last Kiss 的字体一直没有找到，特点是 无衬线、超粗、手写体 a

**Comment by yihleego** [comment]
应该就是这两个字体中的其中一个

**ITC Avant Garde Gothic Paneuropean Bold**
![image](https://user-images.githubusercontent.com/21337386/184298444-8d4de822-e13a-434d-bd5e-cf355fc1c8ee.png)
https://www.myfonts.com/products/paneuropean-bold-itc-avant-garde-gothic-paneuropean-370257


**ITC Avant Garde Gothic Bold**
![image](https://user-images.githubusercontent.com/21337386/184298461-6017d96e-548e-475b-a28a-210f66c0412a.png)
https://www.myfonts.com/products/bold-avant-garde-gothic-370154

**Comment by itorr** [comment]
> 好像是 ITC Avant Garde Gothic Paneuropean Bold

感谢回应！！
这个字体系列各处特征都符合 CD 上所用字体，唯一的小问题就是字重上稍微轻了那么一些，翻了一下 具体在 CD 上使用的应该是 `ITC Avant Garde Gothic Bold`
<img width="591" alt="image" src="https://user-images.githubusercontent.com/1933673/184298817-b90e4cdb-a045-461d-95b2-3eeffef36ee5.png">

超感谢！可以去做 logo 了ψ(｀∇´)ψ

**Comment by itorr** [comment]
https://github.com/itorr/one-last-image/commit/a3243eddbcbec2a40bea438cb30c67d792ad8d01 
Co-authored-by 失败😱 可能是邮箱不正确？
